import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src='' strategy='lazyOnload'></Script>
     
      <main className={styles.main}>
        <h1 className={styles.title}>
         Coders
        </h1>

        <p className={styles.description}>
        Here is the Coders Home Page
        </p>

        <div className={styles.blog__container}>
          <div className={styles.blog__cards}>
            <h2>Learn Js</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos eius pariatur necessitatibus ad magnam fuga temporibus provident, distinctio numquam natus reprehenderit corrupti assumenda sapiente et magni voluptas molestias illum tenetur delectus ab, suscipit eos?</p>
          </div>
          <div className={styles.blog__cards}>
            <h2>Learn Js</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos eius pariatur necessitatibus ad magnam fuga temporibus provident, distinctio numquam natus reprehenderit corrupti assumenda sapiente et magni voluptas molestias illum tenetur delectus ab, suscipit eos?</p>
          </div>
          <div className={styles.blog__cards}>
            <h2>Learn Js</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos eius pariatur necessitatibus ad magnam fuga temporibus provident, distinctio numquam natus reprehenderit corrupti assumenda sapiente et magni voluptas molestias illum tenetur delectus ab, suscipit eos?</p>
          </div>
        </div>
      </main>
    </div>
  )
}
